// <auto-generated />
using System;
using InvoiceManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvoiceManagementSystem.Migrations
{
    [DbContext(typeof(InvoiceManagementSystemContext))]
    [Migration("20221204194614_loginDBRealy")]
    partial class loginDBRealy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InvoiceManagementSystem.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AdminID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApartmentBlock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ApartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.Dues", b =>
                {
                    b.Property<int>("DuesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DuesID");

                    b.HasIndex("UserID");

                    b.ToTable("Dues");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.ElectricityBill", b =>
                {
                    b.Property<int>("ElectricityBillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ElectricityBillCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ElectricityBillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElectricityBillDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElectricityBillPrice")
                        .HasColumnType("int");

                    b.Property<string>("ElectricityBillSequenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElectricityBillSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ElectricityBillStatus")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ElectricityBillID");

                    b.HasIndex("UserID");

                    b.ToTable("ElectricityBills");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.NaturalGasBill", b =>
                {
                    b.Property<int>("NaturalGasBillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NaturalGasBillCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NaturalGasBillDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NaturalGasBillPrice")
                        .HasColumnType("int");

                    b.Property<string>("NaturalGasBillSequenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaturalGasBillSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NaturalGasBillStatus")
                        .HasColumnType("bit");

                    b.Property<string>("NaturalGasBilllDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NaturalGasBillID");

                    b.HasIndex("UserID");

                    b.ToTable("NaturalGasBills");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Todoes");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("ApartmentOwner")
                        .HasColumnType("bit");

                    b.Property<string>("CarsPlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.WaterBill", b =>
                {
                    b.Property<int>("WaterBillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WaterBillCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WaterBillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WaterBillDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WaterBillPrice")
                        .HasColumnType("int");

                    b.Property<string>("WaterBillSequenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterBillSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WaterBillStatus")
                        .HasColumnType("bit");

                    b.HasKey("WaterBillID");

                    b.HasIndex("UserID");

                    b.ToTable("WaterBills");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.Apartment", b =>
                {
                    b.HasOne("InvoiceManagementSystem.Models.User", "User")
                        .WithMany("Apartment")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.Dues", b =>
                {
                    b.HasOne("InvoiceManagementSystem.Models.User", "User")
                        .WithMany("Dues")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.ElectricityBill", b =>
                {
                    b.HasOne("InvoiceManagementSystem.Models.User", "User")
                        .WithMany("ElectricityBill")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.NaturalGasBill", b =>
                {
                    b.HasOne("InvoiceManagementSystem.Models.User", "User")
                        .WithMany("NaturalGasBill")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.WaterBill", b =>
                {
                    b.HasOne("InvoiceManagementSystem.Models.User", "User")
                        .WithMany("WaterBill")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceManagementSystem.Models.User", b =>
                {
                    b.Navigation("Apartment");

                    b.Navigation("Dues");

                    b.Navigation("ElectricityBill");

                    b.Navigation("NaturalGasBill");

                    b.Navigation("WaterBill");
                });
#pragma warning restore 612, 618
        }
    }
}
